/**
 * SalesLogix API
 * Allows to access SalesLogix information and reports Allows to access SalesLogix information and reports
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface Hipaadocument {
    

    documentId?: string;

    duration?: Date;

    includeInPackage?: boolean;

    sentInPackage?: boolean;

    sentOn?: Date;

    replacedDocumentId?: string;

    documentType?: Hipaadocument.DocumentTypeEnum;

    doctorId?: string;

    approvedOnPackage?: boolean;

    /**
     * On SalesLogix
     */
    referenceId?: string;

    hipaaRequestId?: string;

    id?: string;
}
export namespace Hipaadocument {

    export enum DocumentTypeEnum { 
        FinalPDF = <any> 'FinalPDF',
        Label = <any> 'Label',
        Hipaa = <any> 'Hipaa',
        PropHipaa = <any> 'PropHipaa',
        W9 = <any> 'W9',
        DOB = <any> 'DOB',
        SSN = <any> 'SSN',
        Custom = <any> 'Custom',
    }
}
