/**
 * SalesLogix API
 * Allows to access SalesLogix information and reports Allows to access SalesLogix information and reports
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
'use strict';
var HipaarequestInput;
(function (HipaarequestInput) {
    (function (ActionEnum) {
        ActionEnum[ActionEnum["Request"] = 'Request'] = "Request";
        ActionEnum[ActionEnum["RequestRedacted"] = 'RequestRedacted'] = "RequestRedacted";
        ActionEnum[ActionEnum["u$s50check"] = 'u$s50check'] = "u$s50check";
        ActionEnum[ActionEnum["Call"] = 'Call'] = "Call";
        ActionEnum[ActionEnum["Skip"] = 'Skip'] = "Skip";
    })(HipaarequestInput.ActionEnum || (HipaarequestInput.ActionEnum = {}));
    var ActionEnum = HipaarequestInput.ActionEnum;
    (function (StateEnum) {
        StateEnum[StateEnum["NotSent"] = 'NotSent'] = "NotSent";
        StateEnum[StateEnum["Sent"] = 'Sent'] = "Sent";
        StateEnum[StateEnum["Undeliverable"] = 'Undeliverable'] = "Undeliverable";
        StateEnum[StateEnum["NoResponse"] = 'NoResponse'] = "NoResponse";
        StateEnum[StateEnum["Responsed"] = 'Responsed'] = "Responsed";
        StateEnum[StateEnum["Completed"] = 'Completed'] = "Completed";
        StateEnum[StateEnum["Ended"] = 'Ended'] = "Ended";
    })(HipaarequestInput.StateEnum || (HipaarequestInput.StateEnum = {}));
    var StateEnum = HipaarequestInput.StateEnum;
})(HipaarequestInput = exports.HipaarequestInput || (exports.HipaarequestInput = {}));
//# sourceMappingURL=HipaarequestInput.js.map