/**
 * SalesLogix API
 * Allows to access SalesLogix information and reports Allows to access SalesLogix information and reports
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface Policy {
    

    id?: string;

    client?: models.Client;

    owner?: models.Owner;

    insured?: models.Insured;

    carrier?: models.Carrier;

    number?: string;

    currentPremium?: models.PolicyPremium;

    insuredAdditional?: models.Insured;

    anniversaryDate?: Date;

    deathBenefit?: number;

    type?: Policy.TypeEnum;

    shadow?: string;

    calculationMethod?: Policy.CalculationMethodEnum;

    hasStream?: boolean;

    totalPremiumsPaid?: number;

    products?: Array<models.Policyproduct>;

    premiumAdvDate?: Date;
}
export namespace Policy {

    export enum TypeEnum { 
        UL = <any> 'UL',
        VUL = <any> 'VUL',
        WHOLE = <any> 'WHOLE',
    }

    export enum CalculationMethodEnum { 
        Stream = <any> 'Stream',
        COI = <any> 'COI',
    }
}
