/**
 * SalesLogix API
 * Allows to access SalesLogix information and reports Allows to access SalesLogix information and reports
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface PremiumRequestBatch {
    

    id?: string;

    /**
     * Batch position.
     */
    position?: number;

    /**
     * Documents attached to this batch.
     */
    documents?: Array<models.Document>;

    /**
     * Policies attached to this batch.
     */
    policies?: Array<models.PremiumRequestPolicy>;

    /**
     * Current state of the batch
     */
    state?: PremiumRequestBatch.StateEnum;

    /**
     * Payment date
     */
    paymentDate?: Date;

    /**
     * Emai confirmation sent date
     */
    sentOn?: Date;

    /**
     * Payment confirmation date
     */
    confirmedOn?: Date;

    /**
     * Date of rejection
     */
    rejectedOn?: Date;
}
export namespace PremiumRequestBatch {

    export enum StateEnum { 
        Pending = <any> 'Pending',
        Sent = <any> 'Sent',
        Confirmed = <any> 'Confirmed',
        Rejected = <any> 'Rejected',
    }
}
